# settings
server:
  port: 8100
spring:
#  profiles:
#    active: local
  config:
    import: "optional:configserver:http://localhost:8089/"
  application:
    name: macadamia_api
  cloud:
    config:
      name: macadamia_api
      profile: local
      request-connect-timeout: 12000
      request-read-timeout: 10000
  security:
    jwt:
      refresh-expiration-time: 1
base.end.point: "http://localhost:8282"